### ISSUE TITLE
Example of Adding Custom Field

### ISSUE THREAD

**Issue by Bitling** [davidcoallier/Services_Capsule#6]
/**
     \* Add a new Custom field to a party
     *
     \* This method is used to create a new custom field for a party.
     *
     \* @link /api/party/{party-id}/customfield
     \* @throws Services_Capsule_RuntimeException
     *
     \* @param  double       $partyId       The party id to create the new field on.
     \* @param  array        $fields        An assoc array of fields to add in the new
     \*                                     customField
     *
     \* @return mixed bool|stdClass         A stdClass object containing the information from
     \*                                     the json-decoded response from the server.
     */
According to documentation I have passed parameters such as:
$customfield_variable = array('tag'=>'Lead','label'=>'Email_Flag','text' => '77777','boolean'=>'true');
$capsule->customfield->add($partyId,$customfield_variable);
Output while debussing 
echo '<pre>';print_r($customField);echo '</pre>';
Array
(
    [customField] => Array
        (
            [tag] => Lead
            [label] => Email_Flag
            [text] => 77777
            [boolean] => true
        )

)
But not created that custom field in Lead Tag of that Person.

**Comment by nolan-interactive** [comment]
Did you try?

$capsule->party->customfield->add($PartyID, $Field);

Pass in $Field as an array of customFields.
